/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "mock_temp.h"

static const char* CMockString_retVal_addition = "retVal_addition";
static const char* CMockString_x = "x";
static const char* CMockString_y = "y";

typedef struct _CMOCK_retVal_addition_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  DUMMY8 ReturnVal;
  int CallOrder;
  DUMMY8 Expected_x;
  DUMMY8 Expected_y;
  char IgnoreArg_x;
  char IgnoreArg_y;

} CMOCK_retVal_addition_CALL_INSTANCE;

static struct mock_tempInstance
{
  char retVal_addition_IgnoreBool;
  DUMMY8 retVal_addition_FinalReturn;
  char retVal_addition_CallbackBool;
  CMOCK_retVal_addition_CALLBACK retVal_addition_CallbackFunctionPointer;
  int retVal_addition_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE retVal_addition_CallInstance;
} Mock;

extern jmp_buf AbortFrame;
extern int GlobalExpectCount;
extern int GlobalVerifyOrder;

void mock_temp_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.retVal_addition_CallInstance;
  if (Mock.retVal_addition_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_retVal_addition);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.retVal_addition_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void mock_temp_Init(void)
{
  mock_temp_Destroy();
}

void mock_temp_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
  GlobalExpectCount = 0;
  GlobalVerifyOrder = 0;
}

DUMMY8 retVal_addition(DUMMY8 x, DUMMY8 y)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_retVal_addition_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_retVal_addition);
  cmock_call_instance = (CMOCK_retVal_addition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.retVal_addition_CallInstance);
  Mock.retVal_addition_CallInstance = CMock_Guts_MemNext(Mock.retVal_addition_CallInstance);
  if (Mock.retVal_addition_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.retVal_addition_FinalReturn;
    memcpy((void*)(&Mock.retVal_addition_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(DUMMY8[sizeof(cmock_call_instance->ReturnVal) == sizeof(DUMMY8) ? 1 : -1])); /* add DUMMY8 to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.retVal_addition_CallbackBool &&
      Mock.retVal_addition_CallbackFunctionPointer != NULL)
  {
    DUMMY8 cmock_cb_ret = Mock.retVal_addition_CallbackFunctionPointer(x, y, Mock.retVal_addition_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (cmock_call_instance->CallOrder > ++GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledEarly);
  if (cmock_call_instance->CallOrder < GlobalVerifyOrder)
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLate);
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_x)
  {
    UNITY_SET_DETAILS(CMockString_retVal_addition,CMockString_x);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_x), (void*)(&x), sizeof(DUMMY8), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_y)
  {
    UNITY_SET_DETAILS(CMockString_retVal_addition,CMockString_y);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_y), (void*)(&y), sizeof(DUMMY8), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.retVal_addition_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.retVal_addition_CallbackFunctionPointer(x, y, Mock.retVal_addition_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_retVal_addition(CMOCK_retVal_addition_CALL_INSTANCE* cmock_call_instance, DUMMY8 x, DUMMY8 y);
void CMockExpectParameters_retVal_addition(CMOCK_retVal_addition_CALL_INSTANCE* cmock_call_instance, DUMMY8 x, DUMMY8 y)
{
  memcpy((void*)(&cmock_call_instance->Expected_x), (void*)(&x),
         sizeof(DUMMY8[sizeof(x) == sizeof(DUMMY8) ? 1 : -1])); /* add DUMMY8 to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_x = 0;
  memcpy((void*)(&cmock_call_instance->Expected_y), (void*)(&y),
         sizeof(DUMMY8[sizeof(y) == sizeof(DUMMY8) ? 1 : -1])); /* add DUMMY8 to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_y = 0;
}

void retVal_addition_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, DUMMY8 cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_retVal_addition_CALL_INSTANCE));
  CMOCK_retVal_addition_CALL_INSTANCE* cmock_call_instance = (CMOCK_retVal_addition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.retVal_addition_CallInstance = CMock_Guts_MemChain(Mock.retVal_addition_CallInstance, cmock_guts_index);
  Mock.retVal_addition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.retVal_addition_IgnoreBool = (char)1;
}

void retVal_addition_CMockStopIgnore(void)
{
  if(Mock.retVal_addition_IgnoreBool)
    Mock.retVal_addition_CallInstance = CMock_Guts_MemNext(Mock.retVal_addition_CallInstance);
  Mock.retVal_addition_IgnoreBool = (char)0;
}

void retVal_addition_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, DUMMY8 cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_retVal_addition_CALL_INSTANCE));
  CMOCK_retVal_addition_CALL_INSTANCE* cmock_call_instance = (CMOCK_retVal_addition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.retVal_addition_CallInstance = CMock_Guts_MemChain(Mock.retVal_addition_CallInstance, cmock_guts_index);
  Mock.retVal_addition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void retVal_addition_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, DUMMY8 x, DUMMY8 y, DUMMY8 cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_retVal_addition_CALL_INSTANCE));
  CMOCK_retVal_addition_CALL_INSTANCE* cmock_call_instance = (CMOCK_retVal_addition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.retVal_addition_CallInstance = CMock_Guts_MemChain(Mock.retVal_addition_CallInstance, cmock_guts_index);
  Mock.retVal_addition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->CallOrder = ++GlobalExpectCount;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_retVal_addition(cmock_call_instance, x, y);
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(DUMMY8[sizeof(cmock_to_return) == sizeof(DUMMY8) ? 1 : -1])); /* add DUMMY8 to :treat_as_array if this causes an error */
}

void retVal_addition_AddCallback(CMOCK_retVal_addition_CALLBACK Callback)
{
  Mock.retVal_addition_IgnoreBool = (char)0;
  Mock.retVal_addition_CallbackBool = (char)1;
  Mock.retVal_addition_CallbackFunctionPointer = Callback;
}

void retVal_addition_Stub(CMOCK_retVal_addition_CALLBACK Callback)
{
  Mock.retVal_addition_IgnoreBool = (char)0;
  Mock.retVal_addition_CallbackBool = (char)0;
  Mock.retVal_addition_CallbackFunctionPointer = Callback;
}

void retVal_addition_CMockIgnoreArg_x(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_retVal_addition_CALL_INSTANCE* cmock_call_instance = (CMOCK_retVal_addition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.retVal_addition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_x = 1;
}

void retVal_addition_CMockIgnoreArg_y(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_retVal_addition_CALL_INSTANCE* cmock_call_instance = (CMOCK_retVal_addition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.retVal_addition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_y = 1;
}

